### ISSUE TITLE
Move this repo to ipfs-shipyard and make it public?

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/pm-peer-pad#27]
Hi all! I feel that now that we have shipped the first version of PeerPad successfully (goal was by Mozfest, now we don't have any tight deadline with extreme focus required), there is no reason why not to move this repo to ipfs-shipyard and make it public so that others can subscribe to it as well. 

Thoughts?

**Comment by daviddias** [comment]
> @daviddias let's move it over

Done:) 

> one caveat: if we make this repo public, we need to be careful to make linked materials (wireframes, design docs, etc) public as well -- this could be tricky with e.g. InVision workspaces

If the app doesn't support it, we can always try to accommodate case by case (e.g. give an account to a user that is heavily contributing or just exporting the assets in a different way.)

**Comment by parkan** [comment]
✨
