### ISSUE TITLE
Remove stale frontend elements

### ISSUE THREAD

**Issue by parkan** [ipfs-shipyard/pm-peer-pad#35]
A lot of the peerpad.net site components have become stale, were never implemented, or aren't well-aligned with the immediate goal of using the tool for internal notetaking. Let's cull those so we can focus on the core product:

- [x] **Landing Page:** the landing page clearly had a lot of work put into it, but it's out of date (still talks about Y.js), doesn't bring much value to internal users, and creates an extra step before you get your pad. Other *pad products tend to only deploy a landing page of any kind of if they want you to pay or log in, otherwise booting to a new document is common (this can be prefilled with some explanatory copy, e.g. https://dillinger.io/). Let's bypass this page during internal testing and come back to it fresh afterwards.
- [x] **"PeerPad is Alpha" banner:** important warning but well-understood by internal users (and kind of demoralizing), let's make it dismissable
- [x] **Files/Settings/Shortcuts:** never implemented, can hide until and unless we build them out
- [x] **"Math Pad" mode:** I guess this was meant to be a different editor UI (maybe like LaTeX/overleaf?) but never seems to have been implemented. Removing the mode choice also makes booting directly to a document unambiguous.

Most of these are just deletions in react templates or otherwise simple work, probably a couple of hours at the most. I know a lot of work has gone into the original prototype version, but it is no longer well-aligned with our immediate goals for the product.

Completing them will clear the path to #25, which will provide us with invaluable user feedback to inform further UX work, and a cleaner base for new designs on (#31).

**Comment by victorb** [comment]
One option could be to leave peerpad.net as-is right now (`production` branch in the GitHub repository) and exclusively work from `master` branch. Master branch gets deployed to dev.peerpad.net, and there is where we can streamline it (open directly to new pad, remove verbose warnings and similar)

**Comment by victorb** [comment]
PR here: https://github.com/ipfs-shipyard/peer-pad/pull/238

**Comment by victorb** [comment]
PR is currently waiting review. In the meantime, you can review the new versions UI here: https://ipfs.io/ipfs/QmWMDrh8yHuyqhFYUvH4BJ27pKBbCUuKYzpP3KgRAH1QQV/ < checks all the boxes in the opening issue here

**Comment by victorb** [comment]
The PR has been merged now and the changes mentioned in this issue have been deployed to js.peerpad.net! Unfortunately, something is wrong with the certificates on that site, working on fixing that.

I'd like to have confirmation on the following:

> One option could be to leave peerpad.net as-is right now (production branch in the GitHub repository) and exclusively work from master branch. Master branch gets deployed to dev.peerpad.net, and there is where we can streamline it (open directly to new pad, remove verbose warnings and similar)

^ would mean that for internal testing, we tell people to use dev.peerpad.net instead, and we leave peerpad.net in it's current state, for visitors to understand peerpad before using it.

**Comment by parkan** [comment]
do we have any analytics on the live site? I'm curious if it gets a meaningful amount of non-PL usage

**Comment by parkan** [comment]
> The PR has been merged now and the changes mentioned in this issue have been deployed to js.peerpad.net! Unfortunately, something is wrong with the certificates on that site, working on fixing that.

js.peerpad.net doesn't seem to be running a web server, do you mean dev.peerpad.net?

would be nice to have a shorter redirect url for this, do we have an internal shortlinker?

> 
> I'd like to have confirmation on the following:
> ...
> ^ would mean that for internal testing, we tell people to use dev.peerpad.net instead, and we leave peerpad.net in it's current state, for visitors to understand peerpad before using it.

how about this: we can tag f29acedbb76ddca1f208df5fad7257a9c1585311 as "production" and leave it deployed on the main site with the explainer landing page, etc

I don't think it's worth maintaining it as an active branch/backporting work from master on an ongoing basis, unless we see significant usage (or a really bad vulnerability)

**Comment by victorb** [comment]
@parkan Ah, yes, I meant dev.peerpad.net. Don't think it's long enough to warrant a shorter link...

My suggestion is to leave the `production` as-is today, which means being locked to commit https://github.com/ipfs-shipyard/peer-pad/commit/2727041096b2b1e77d0685f61a70ed5ecdb88343

Agree with not worth backporting fixes unless we see high impact security issues.

**Comment by parkan** [comment]
oops, you're right, I had the wrong parent, 2727041 is right

reasoning for shortlink (or more unique prefix) is to minimize keystrokes to load the site, there's probably a lot of `dev...` prefixes in most people's histories

not a huge deal tho! marking this as done

**Comment by victorb** [comment]
Yeah, my fear about link shorteners is that eventually they die, and all the redirects die with them. Usually just better to use the proper link directly. We can add aliases to `test.peerpad.net` or whatever in the future. 

Missed this question before:

> do we have any analytics on the live site? I'm curious if it gets a meaningful amount of non-PL usage

AFAIK, we don't. We do have Rollbar but that only gives us the errors.

[Once the pinner has metrics](https://github.com/ipfs-shipyard/peer-star-app/pull/165), we can get some basic information from that, first `total peers` and `total collaborations`, in the future we can expand it to contain more information.

**Comment by parkan** [comment]
sgtm
